### ISSUE TITLE
Throw Exception instead of asserting if connection was successful

### ISSUE THREAD

**Issue by the-kenny** [tatut/clj-chrome-devtools#1]
https://github.com/tatut/clj-chrome-devtools/blob/704e1e611fa524e2692cc0e857109514fa3a19dc/src/clj_chrome_devtools/impl/connection.clj#L57-L58

If you spawn a headless chrome and connect right away it isn't ready and the quoted code above will run. This will throw an `AssertionError` where a normal `RuntimeException` or some subclass would be much more appropriate.

**Comment by tatut** [comment]
That's a good point. I actually have code to wait for the spawned Chrome to be ready in the clojure.test fixture.

Perhaps that functionality should be in connect itself.

**Comment by the-kenny** [comment]
Sounds reasonable, but I think it's best to make this automatic retry
behavior optional.

Am 24.08.2017 14:58 schrieb "Tatu Tarvainen" <notifications@github.com>:

**Comment by tatut** [comment]
Agreed. In any case, I'll change the assertion to throw `ex-info` instead.
