### ISSUE TITLE
Help wanted : Could you please clarify how to run the test?

### ISSUE THREAD

**Issue by 1v1a3x** [tatut/clj-chrome-devtools#12]
Hello guys,

I'm getting the following exception when trying to execute the clj-chrome-devtools.chrome-test/simple-page-load with `lein eftest` command (or just from IntelliJ Idea / Cursive plugin).

`CompilerException java.lang.IllegalArgumentException: Cannot open <nil> as a Reader., compiling:(clj_chrome_devtools/commands/dom.clj:4:1)`

Could you please help me to figure it out how can I execute the test example? 
Thank you.

**Comment by tatut** [comment]
Sorry, I don't use Cursive or eftest.

You can see an example in my other project `tuck` being run here: https://circleci.com/gh/tatut/tuck/48

**Comment by 1v1a3x** [comment]
Thank you a lot for helping me Tatu!
