### ISSUE TITLE
Support running deps.edn/figwheel-main based tests

### ISSUE THREAD

**Issue by tatut** [tatut/clj-chrome-devtools#22]
Current `clojure.test` integration has support for running cljs tests as part of a clojure test suite and supports leiningen projects.

Add support for building and running tests for deps.edn/figwheel-main based projects.

**Comment by tatut** [comment]
Or implement a cljs repl environment that can be used with kaocha

**Comment by aviflax** [comment]
Seems like this might have been partly enabled by #26, which added a simple (~simplistic) way to run the tests — I don’t know if that test environment supports ClojureScript, but maybe? If not, then Kaocha is probably the way to go.

**Comment by tatut** [comment]
There seems to lots of work in the testing area in other projects.

I'm closing this as I don't plan to add more here.
